### ISSUE TITLE
مشکل nativefier

### ISSUE THREAD

**Issue by markazie** [milani/nodejs.ir#45]
سلام من تازه میخوام با node.js 
کار کنم وقتی دستورهای زیر رو وارد می کنم که مثال ذکر شده در خود سایتش هست
$ nativefier "http://example.com.com"
or
$ nativefier maps.google.com
ارور زیر رو به من میده
SyntaxError: Unexpected indentifier
at Object.exports.createScript (vm.js:24:10)
at REPLServer.defaultEval (repl.js:225:25)
at bound (domain.js:287:14)
at REPLServer.runBound as eval
at REPLServer. (repl.js:417:12)
at emitOne (events.js:82:20)
at REPLServer.emit (events.js:169:7)
at REPLServer.Interface._onLine (readline.js:210:10)
at REPLServer.Interface._line (readline.js:549:8)
at REPLServer.Interface._ttyWrite (readline.js:826:14)

لطفا راهنمایی کنید
با تشکر

**Comment by arastu** [comment]
لطفا این سوال را در میلینگ لیست بپرسید.
http://groups.google.com/group/nodejs-fa
